floodrelief/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view()),
]

mainapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('request/', views.CreateRequest.as_view(), name='requestview'),
    # path('volunteer/', views.Maintenance.as_view(), name='registerview'),
    path('volunteer/', views.RegisterVolunteer.as_view(), name='registerview'),
    path('requests/', views.request_list, name='requestlistview'),
    url(r'request_details/(?P<request_id>\d+)/$', views.request_details, name='requestdetailsview'),
    path('contactus/', views.districtmanager_list, name='contactus'),
    path('reg_success/', views.RegSuccess.as_view(), name='reg_successview'),
    path('req_sucess/', views.ReqSuccess.as_view(), name='req_sucessview'),
    path('district_needs/', views.DistNeeds.as_view(), name='distneedsview'),
    path('reg_contrib/', views.RegisterContributor.as_view(), name='reg_contribview'),
    path('contrib_success/', views.ContribSuccess.as_view(), name='contribsucessview'),
    path('disclaimer/', views.DisclaimerPage.as_view(), name='disclaimer'),
    path('ieee/', views.AboutIEEE.as_view(), name='aboutieee'),
    path('data/' , views.mapdata , name="mapdata"),
    path('map/' , views.mapview , name="mapview"),
    path('dmodash/' , views.dmodash , name="DMODash"),
    path('dmoinfo/' , views.dmoinfo , name="DMOInfo" ),
    path('error/' , views.error , name="errorview" ),
    path('add_person/', views.AddPerson.as_view(), name='add_person'),
    path('login/', auth_views.LoginView.as_view(template_name='mainapp/login.html'),name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('relief_camps/', views.relief_camps, name='relief_camps'),
    path('find_people/', views.find_people, name='find_people'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

districts = (
    ('alp','Alappuzha - ആലപ്പുഴ'),
    ('ekm','Ernakulam - എറണാകുളം'),
    ('idk','Idukki - ഇടുക്കി'),
    ('knr','Kannur - കണ്ണൂർ'),
    ('ksr','Kasaragod - കാസർഗോഡ്'),
    ('kol','Kollam - കൊല്ലം'),
    ('ktm','Kottayam - കോട്ടയം'),
    ('koz','Kozhikode - കോഴിക്കോട്'),
    ('mpm','Malappuram - മലപ്പുറം'),
    ('pkd','Palakkad - പാലക്കാട്'),
    ('ptm','Pathanamthitta - പത്തനംതിട്ട'),
    ('tvm','Thiruvananthapuram - തിരുവനന്തപുരം'),
    ('tcr','Thrissur - തൃശ്ശൂർ'),
    ('wnd','Wayanad - വയനാട്'),
)

status_types =(
    ('new', 'New'),
    ('pro', 'In progess'),
    ('sup', 'Supplied'),
)

contrib_status_types =(
    ('new', 'New'),
    ('ful', 'Fullfilled'),
)

vol_categories = (
    ('dcr', 'Doctor'),
    ('hsv', 'Health Services'),
    ('elw', 'Electrical Works'),
    ('mew', 'Mechanical Work'),
    ('cvw', 'Civil Work'),
    ('plw', 'Plumbing work'),
    ('vls', 'Vehicle Support'),
    ('ckg', 'Cooking'),
    ('rlo', 'Relief operation'),
    ('cln', 'Cleaning'),
    ('bot', 'Boat Service'),
    ('rck', 'Rock Climbing'),
    ('oth', 'Other')
)

gender =(
    (0,'Male'),
    (1,'Female'),
    (2,'Others')
)

class Request(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name='Districts - ജില്ല'
    )
    location = models.CharField(max_length=500,verbose_name='Location - സ്ഥലം')
    requestee = models.CharField(max_length=100,verbose_name='Requestee - അപേക്ഷകന്‍റെ പേര്')
    requestee_phone = models.CharField(max_length=10,verbose_name='Requestee Phone - അപേക്ഷകന്‍റെ ഫോണ്‍ നമ്പര്‍')
    latlng = models.CharField(max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ ', blank=True)
    latlng_accuracy = models.CharField(max_length=100, verbose_name='GPS Accuracy - GPS കൃത്യത ', blank=True)
    is_request_for_others = models.BooleanField(verbose_name='Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു  ', default=False)

    needwater = models.BooleanField(verbose_name='Water - വെള്ളം')
    needfood = models.BooleanField(verbose_name='Food - ഭക്ഷണം')
    needcloth = models.BooleanField(verbose_name='Clothing - വസ്ത്രം')
    needmed = models.BooleanField(verbose_name='Medicine - മരുന്നുകള്‍')
    needtoilet = models.BooleanField(verbose_name='Toiletries - ശുചീകരണ സാമഗ്രികള്‍ ')
    needkit_util = models.BooleanField(verbose_name='Kitchen utensil - അടുക്കള സാമഗ്രികള്‍')
    needrescue = models.BooleanField(verbose_name='Need rescue - രക്ഷാപ്രവർത്തനം ആവശ്യമുണ്ട്')

    detailwater = models.CharField(max_length=250, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailfood = models.CharField(max_length=250, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailcloth = models.CharField(max_length=250, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailmed = models.CharField(max_length=250, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്‍റെ  വിവരങ്ങള്‍', blank=True)
    detailtoilet = models.CharField(max_length=250, verbose_name='Details for required toiletries - ആവശ്യമായ  ശുചീകരണ സാമഗ്രികള്‍', blank=True)
    detailkit_util = models.CharField(max_length=250, verbose_name='Details for required kitchen utensil - ആവശ്യമായ അടുക്കള സാമഗ്രികള്‍', blank=True)
    detailrescue = models.CharField(max_length=250, verbose_name='Details for rescue action - രക്ഷാപ്രവർത്തനം വിവരങ്ങള്', blank=True)

    needothers = models.CharField(max_length=500, verbose_name="Other needs - മറ്റു ആവശ്യങ്ങള്‍", blank=True)
    status = models.CharField(
        max_length = 10,
        choices = status_types,
        default = 'new'
    )
    supply_details = models.CharField(max_length=100, blank=True)
    dateadded = models.DateTimeField(auto_now_add=True)

    def summarise(self):
        out = ""
        if(self.needwater):
            out += "Water Requirements :\n {}".format(self.detailwater)
        if(self.needfood):
            out += "\nFood Requirements :\n {}".format(self.detailfood)
        if(self.needcloth):
            out += "\nCloth Requirements :\n {}".format(self.detailcloth)
        if(self.needmed):
            out += "\nMedicine Requirements :\n {}".format(self.detailmed)
        if(self.needtoilet):
            out += "\nToilet Requirements :\n {}".format(self.detailtoilet)
        if(self.needkit_util):
            out += "\nKit Requirements :\n {}".format(self.detailkit_util)
        if(len(self.needothers.strip()) != 0):
            out += "\nOther Needs :\n {}".format(self.needothers)
        return out

    def __str__(self):
        return self.get_district_display() + ' ' + self.location

class Volunteer(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    organisation = models.CharField(max_length=250, verbose_name="Organization (സംഘടന) / Institution")
    address = models.TextField()
    area = models.CharField(
        max_length = 15,
        choices = vol_categories,
        verbose_name = "Area of volunteering"
    )
    is_spoc = models.BooleanField(default=False, verbose_name="Is point of contact")
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Contributor(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    address = models.TextField()
    commodities = models.TextField(verbose_name="What you can contribute. ( സംഭാവന ചെയ്യാന്‍ ഉദ്ദേശിക്കുന്ന സാധനങ്ങള്‍ ) -- Eg: Shirts, torches etc ")
    status = models.CharField(
        max_length = 10,
        choices = contrib_status_types,
        default = 'new'
    )

    def __str__(self):
        return self.name + ' ' + self.get_district_display()


class DistrictManager(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' ' + self.get_district_display()

class DistrictNeed(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    needs = models.TextField(verbose_name="Items required")
    cnandpts = models.TextField(verbose_name="Contacts and collection points") #contacts and collection points

    def __str__(self):
        return self.get_district_display()


class DistrictCollection(models.Model):
    district = models.CharField(
        max_length=15,
        choices=districts
    )
    collection = models.TextField(
        verbose_name="Details of collected items"
    )

class RescueCamp(models.Model):
    verbose_name = 'Relief Camp'
    name = models.CharField(max_length=50,verbose_name="Name")
    location = models.TextField(verbose_name="Address",blank=True,null=True)
    district = models.CharField(
        max_length=15,
        choices=districts
    )
    taluk = models.CharField(max_length=50,verbose_name="Taluk")
    village = models.CharField(max_length=50,verbose_name="Village")
    contacts = models.TextField(verbose_name="Phone Numbers",blank=True,null=True)
    data_entry_user = models.ForeignKey(User,models.SET_NULL,blank=True,null=True)
    map_link = models.CharField(max_length=250, verbose_name='Map link',blank=True,null=True,help_text="Copy and paste the full Google Maps link")
    latlng = models.CharField(max_length=100, verbose_name='GPS Coordinates', blank=True,help_text="Comma separated latlng field. Leave blank if you don't know it")
    class Meta:
        verbose_name = 'Relief Camp'
    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=30,blank=False,null=False,verbose_name="Name - പേര്")
    phone = models.CharField(max_length=11,null=True,blank=True,verbose_name='Mobile - മൊബൈൽ')
    age = models.IntegerField(null=True,blank=True,verbose_name="Age - പ്രായം")
    gender = models.IntegerField(
        choices = gender,
        verbose_name='Gender - ലിംഗം',
        null=True,blank=True
    )
    address = models.TextField(max_length=150,null=True,blank=True,verbose_name="Address - വിലാസം")
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name='District - ജില്ല',
        null=True,blank=True
    )
    notes = models.TextField(max_length=500,null=True,blank=True,verbose_name='Notes - കുറിപ്പുകൾ')
    camped_at = models.ForeignKey(RescueCamp,models.CASCADE,blank=False,null=False,verbose_name='Camp Name - ക്യാമ്പിന്റെ പേര്')
    added_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

mainapp/templates/mainapp/aboutieee.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">About IEEE</h1>
    <p style="font-size:1.7rem;">IEEE– Institute of Electrical and Electronics Engineers, is the world’s largest technical professional society, is continuously promoting the development and application of technology and allied sciences for the benefit of humanity and for the advancement of the profession. Formally started in 1963, IEEE now has 430,000 members spanning across 165 countries of the globe. IEEE fosters the development of standards and advancement of technology for the benifit of humanity.</p>
    <p style="font-size:1.7rem;">
        IEEE Kerala Section, one of the 11 Sections of IEEE in India was founded by the technology giant of Kerala, Late KPP Nambiar in 1983. Several innovations from IEEE Kerala Section in organizing activities for students as well as professionals have been appreciated and replicated by the global IEEE community. Winner of MGA Large Section Award in 2015 and Region 10 (Asia Pacific) Outstanding Large Section Award in 2004, 2009 and 2015, IEEE Kerala Section has been organizing high quality, high impact technical events and humanitarian projects. Please visit our website https://ieeekerala.org/ for more details about the activities of IEEE Kerala section.</p>
</div>
{% endblock %}

mainapp/templates/mainapp/add_person.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block content %}  
  <div class="text-right">
    <a href="/find_people">Search</a> | 
    <a href="/logout">Logout</a>
  </div>

  <h3 class="text-center">
      Person Registration | 
      വ്യക്തിയെ രജിസ്റ്റർ ചെയ്യുക      
  </h3>

  <div class="text-center text-danger">
      {% if messages %}
        {% for message in messages %}
          <h3>{{ message }}</h3>
        {% endfor %}
      {% endif %}
  </div>

  <form method="post"  class="simple-form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-success">
    Submit {% bootstrap_icon "chevron-right" %}
    </button>
    {% endbuttons %}

    <p class="text-center">
        Please enter all available information. This can help relatives find them if required. <br>
        ബന്ധുക്കൾക്ക് ഇവരെ കണ്ടെത്തുന്നതിന് ഇത് സഹായിക്കും
    </p>
  </form> 

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script>
  $('#id_gender_0').parents('.radio').hide();
  $('#id_gender > .radio').removeClass('radio').addClass('radio-inline');
  </script>

{% endblock %}

mainapp/templates/mainapp/contrib_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>Our volunteer will contact you soon for collection</h3>

{% endblock %}

mainapp/templates/mainapp/contributor_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}


  <form method="post">
    <b class="text-center"> You can also contribute to Chief Minister's Fund:<br>
      മുഖ്യമന്തിയുടെ ദുരിതാശ്വാസ നിധിയിലേക്ക് സംഭാവന ചെയ്യാം<br/>
      Account number : 67319948232<br>
      Bank: SBI<br>
      Branch: City Branch, TVM<br>
      IFS Code: SBIN0070028<br>
      <a href="https://donation.cmdrf.kerala.gov.in/">Donate to Chief Minister's Fund Online</a>
    </b><br><br>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
  {% bootstrap_icon "star" %} Submit
  </button>
  {% endbuttons %}
  </form>
<script>
    window.onload = function() {
        $("#id_phone").attr('type', 'number');
    }
</script>
{% endblock %}

mainapp/templates/mainapp/disclaimer.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">Disclaimer</h1>
    <p style="font-size:1.7rem;">This portal has been developed for effective collaboration between various stakeholders such as citizen, Government authorities, various NGOs and volunteers. IEEE makes no representation regarding the completeness, accuracy of any information and data contained on this portal or that such information and data will be error-free. Stakeholders are trying to make their best effort to support, any information received through the portal the requests received through this portal doesn’t warrant any commitment on the services. By using this site you acknowledge that you have read and agree to this</p>
</div>
{% endblock %}

mainapp/templates/mainapp/district_needs.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="">
  <table class="table">
    <tr>
      <th>District</th>
      <th>Items required</th>
      <th>Contacts & Collection points</th>
    </tr>
  {% for item in district_data %}
    <!-- Ernakulam -->
    <tr valign="top">
      <td><strong>{{item.get_district_display}}</strong></td>
      <td>
        {{item.needs|linebreaks}}
      </td>
      <td>
        {{item.cnandpts|linebreaks}}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

mainapp/templates/mainapp/districtmanager_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<p class="text-center">
  Volunteers are available across Kerala. Contact the <u>District level point of contacts</u> for any help. <br/>
  സഹായത്തിനായി വൊളന്‍റീയര്‍മാര്‍ തയ്യാറാണ്. സഹായം ആവശ്യമെങ്കില്‍ ഒരോ ജില്ലയിലെയും നിയോഗിക്കപെട്ട ഉദ്യോഗസ്ഥരുമായി ബന്ധപ്പെടാം
</p>
<form action="" method="get">
       {{ filter.form.as_p }}
       <input type="submit" value="Find contact"/>
 </form>
 <div class="table-responsive">
  <table class="table">
    <tr>
      <th>Name - പേര്</th>
      <th>Phone - ഫോൺ</th>
      <th>Other Contact - മറ്റ് കോൺടാക്റ്റ്</th>
    </tr>
    {% for req in filter.qs %}
        <tr>
          <td>{{ req.name }}</td>
          <td><a href="tel:{{ req.phone }}">{{ req.phone }}</a></td>          <td>{{ req.email }}</td>
        </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

mainapp/templates/mainapp/error.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<div class="row text-center static-page-box">
    <h1 class="text-center">Error</h1>
    <p style="font-size:1.7rem;">{{ error_text }}</p>
</div>
{% endblock %}

mainapp/templates/mainapp/maintenance.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<h2>Volunteer registration will be back soon</h2>
{% endblock %}

mainapp/templates/mainapp/people.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<h3>
    Person Search - വ്യക്തിയെ തിരയുക
</h3>
<p>
    ദുരിതാശ്വാസക്യാമ്പിൽ രജിസ്റ്റർ ചെയ്ത വ്യക്തിയ്ക്കായി തിരയുക
</p>
<div class="row">
    <div class="col-md-4">
        <form action="" method="get">
            Search with name, mobile number etc. <br>
            പേരോ മൊബൈൽ നമ്പറോ ഉപയോഗിച്ച് തിരയാം 
            <hr>
            {{ filter.form.as_p }}

          <button type="submit" class="btn btn-success btn-lg">Search {% bootstrap_icon "chevron-right" %}</button>
      </form>
    </div>
    <div class="col-md-8">
        <div class="table-responsive">
            <table class="table">
              <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Address</th>
                <th>District</th>
                <th>Camp Name</th>
                <th>Notes</th>
                <th>Registered On</th>
              </tr>
              {% for req in data %}
                  <tr>
                    <td>{{ req.name }}</td>
                    <td>{{ req.age }}</td>
                    <td>{{ req.address }}</td>
                    <td>{{ req.get_district_display}}</td>
                    <td>{{ req.camped_at}}</td>
                    <td>{{ req.notes}}</td>
                    <td>{{ req.added_at}}</td>
                  </tr>
              {% endfor %}
            </table>
            
            {% if data.paginator.num_pages > 1 %}
            <div class="pagination" >
              <span class="step-links">
                  {% if data.has_previous %}
                      <a href="?page=1">&laquo; first</a>
                      <a href="?page={{data.previous_page_number}}">previous</a>
                  {% endif %}
            
                  {% for i in data.paginator.page_range %}
                  {% if data.number == i %}
                    <a class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                  {% else %}
                    <a href="?page={{i}}">{{ i }}</a>
                  {% endif %}
                {% endfor %}
            
                  {% if data.has_next %}
                      <a href="?page={{ data.next_page_number }}">next</a>
                      <a href="?page={{ data.paginator.num_pages }}">last &raquo;</a>
                  {% endif %}
              </span>
            </div>
            {% endif %}
          
          </div>
    
      </div>
</div>




{% endblock %}

mainapp/templates/mainapp/reg_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>You have been registered successfully. Please wait for the call for action.</h3>

{% endblock %}

mainapp/templates/mainapp/relief_camps.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>
        Relief Camps | 
        ദുരിതാശ്വാസ ക്യാമ്പുകൾ
</h3>

<div class="row">
    <div class="col-md-4">
        <a class="btn btn-info btn-lg" href="/find_people">
                Person Search - വ്യക്തിയെ തിരയുക
        </a>
    </div>
    <div class="col-md-8 text-right">
        <a class="btn btn-default" href="/add_person" style="margin-top: 5px;">
            Coordinator Login
        </a>
        <p>
          Contact your coordinator to get login details
          <br>
          ലോഗിൻ ഡീറ്റെയിൽസ് ലഭിക്കാൻ കോർഡിനേറ്ററെ സമീപിക്കുക
        </p>
    </div>
</div>

<hr>

<div class="text-center">
  <h4>Select District to see Relief Camps</h4>
</div>

<form action="" method="get">
    {{ filter.form }}
    <button class="btn btn-default" type="submit">Show Relief Camps</button>
</form>

{% if relief_camps.count > 0 %}
<div>
  <table class="table">
    <tr>
      <th>District</th>
      <th>Camp Name</th>
      <th>Map</th>
      <th>Address</th>
      <th>Contact Numbers</th>
      <th>Registrations</th>
    </tr>
  {% for item in relief_camps %}
    <tr valign="top">
      <td><strong>{{ item.get_district_display }}</strong></td>
      <td>
        {{ item.name }}
      </td>
      <td>
        {% if item.map_link %} <a href="{{ item.map_link}}">Map Link</a> {% else %} N/A {% endif %}
      </td>
      <td>
        {{ item.location | linebreaks }}
      </td>
      <td class="phone-links">
        {{ item.contacts | linebreaks }}
      </td>
      <td>
        {{ item.count }}
      </td>
    </tr>
    {% endfor %}
  </table>
</div>
{% elif district_chosen  %}
<div class="text-center text-warning">
  No relief camps listed for this district yet.
</div>
{% endif %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
  $('.phone-links').each(function () {
    var content = $(this).html();
    // Convert 10 digit numbers to links
    links = content.replace(/[0-9 ]{10,15}/g, "<a href=\"tel:$&\">$&</a>");
    $(this).html(links);
  })

</script>
{% endblock %}

mainapp/templates/mainapp/req_success.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<h3>Request successfully registered</h3>

{% endblock %}

mainapp/templates/mainapp/request_details.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

<form action="{%url 'requestlistview' %}" method="get" class="text-center">
       {{ filter.form.as_p }}
       <input value="View requests" class="btn btn-primary" type="submit" />
 </form>
 <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th colspan="2" style="text-align:center;">Request details</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><b> District : </b></td><td>{{ req.get_district_display }}</td>
      </tr>
      <tr>
        <td><b> Location : </b></td><td>{{ req.location }}</td>
      </tr>
      <tr>
        <td><b> GPS Location : </b></td>
        <td>
          {% if not req.is_request_for_others and req.latlng %}
            <a class="btn btn-sm btn-success" href="https://maps.google.com/?q={{ req.latlng }}" target="_blank">Open in maps</a>
            <br>
            Accuracy: {{ req.latlng_accuracy }}
          {% else %}
            NA
          {% endif %}
        </td>
      </tr>
      <tr>
        <td><b> Requestee : </b></td><td>{{ req.requestee }}</td>
      </tr>
      <tr>
        <td><b> Contact number : </b></td><td><a href="tel:{{ req.requestee_phone }}" >{{ req.requestee_phone }}</a></td>
      </tr>
      <tr>
        <td><b> Summary of request : </b></td><td>{{ req.summarise | linebreaks }}</td>
      </tr>
      <tr>
        <td><b> Date : </b></td><td>{{ req.dateadded }}</td>
      </tr>
    </tbody>
  </table>

</div>
{% endblock %}