floodrelief/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
admin.site.site_header = settings.ADMIN_SITE_HEADER

urlpatterns = [
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view()),
]

mainapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('request/', views.CreateRequest.as_view(), name='requestview'),
    # path('volunteer/', views.Maintenance.as_view(), name='registerview'),
    path('volunteer/', views.RegisterVolunteer.as_view(), name='registerview'),
    path('requests/', views.request_list, name='requestlistview'),
    url(r'request_details/(?P<request_id>\d+)/$', views.request_details, name='requestdetailsview'),
    path('contactus/', views.districtmanager_list, name='contactus'),
    path('reg_success/', views.RegSuccess.as_view(), name='reg_successview'),
    path('req_sucess/', views.ReqSuccess.as_view(), name='req_sucessview'),
    path('district_needs/', views.DistNeeds.as_view(), name='distneedsview'),
    path('reg_contrib/', views.RegisterContributor.as_view(), name='reg_contribview'),
    path('contrib_success/', views.ContribSuccess.as_view(), name='contribsucessview'),
    path('disclaimer/', views.DisclaimerPage.as_view(), name='disclaimer'),
    path('ieee/', views.AboutIEEE.as_view(), name='aboutieee'),
    path('data/' , views.mapdata , name="mapdata"),
    path('map/' , views.mapview , name="mapview"),
    path('dmodash/' , views.dmodash , name="DMODash"),
    path('dmoinfo/' , views.dmoinfo , name="DMOInfo" ),
    path('error/' , views.error , name="errorview" ),
    path('add_person/', views.AddPerson.as_view(), name='add_person'),
    path('login/', auth_views.LoginView.as_view(template_name='mainapp/login.html'),name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('relief_camps/', views.relief_camps, name='relief_camps'),
    path('find_people/', views.find_people, name='find_people'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

districts = (
    ('alp','Alappuzha - ആലപ്പുഴ'),
    ('ekm','Ernakulam - എറണാകുളം'),
    ('idk','Idukki - ഇടുക്കി'),
    ('knr','Kannur - കണ്ണൂർ'),
    ('ksr','Kasaragod - കാസർഗോഡ്'),
    ('kol','Kollam - കൊല്ലം'),
    ('ktm','Kottayam - കോട്ടയം'),
    ('koz','Kozhikode - കോഴിക്കോട്'),
    ('mpm','Malappuram - മലപ്പുറം'),
    ('pkd','Palakkad - പാലക്കാട്'),
    ('ptm','Pathanamthitta - പത്തനംതിട്ട'),
    ('tvm','Thiruvananthapuram - തിരുവനന്തപുരം'),
    ('tcr','Thrissur - തൃശ്ശൂർ'),
    ('wnd','Wayanad - വയനാട്'),
)

status_types =(
    ('new', 'New'),
    ('pro', 'In progess'),
    ('sup', 'Supplied'),
)

contrib_status_types =(
    ('new', 'New'),
    ('ful', 'Fullfilled'),
)

vol_categories = (
    ('dcr', 'Doctor'),
    ('hsv', 'Health Services'),
    ('elw', 'Electrical Works'),
    ('mew', 'Mechanical Work'),
    ('cvw', 'Civil Work'),
    ('plw', 'Plumbing work'),
    ('vls', 'Vehicle Support'),
    ('ckg', 'Cooking'),
    ('rlo', 'Relief operation'),
    ('cln', 'Cleaning'),
    ('bot', 'Boat Service'),
    ('rck', 'Rock Climbing'),
    ('oth', 'Other')
)

gender =(
    (0,'Male'),
    (1,'Female'),
    (2,'Others')
)

class Request(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name='Districts - ജില്ല'
    )
    location = models.CharField(max_length=500,verbose_name='Location - സ്ഥലം')
    requestee = models.CharField(max_length=100,verbose_name='Requestee - അപേക്ഷകന്‍റെ പേര്')
    requestee_phone = models.CharField(max_length=10,verbose_name='Requestee Phone - അപേക്ഷകന്‍റെ ഫോണ്‍ നമ്പര്‍')
    latlng = models.CharField(max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ ', blank=True)
    latlng_accuracy = models.CharField(max_length=100, verbose_name='GPS Accuracy - GPS കൃത്യത ', blank=True)
    is_request_for_others = models.BooleanField(verbose_name='Requesting for others - മറ്റൊരാൾക്ക് വേണ്ടി അപേക്ഷിക്കുന്നു  ', default=False)

    needwater = models.BooleanField(verbose_name='Water - വെള്ളം')
    needfood = models.BooleanField(verbose_name='Food - ഭക്ഷണം')
    needcloth = models.BooleanField(verbose_name='Clothing - വസ്ത്രം')
    needmed = models.BooleanField(verbose_name='Medicine - മരുന്നുകള്‍')
    needtoilet = models.BooleanField(verbose_name='Toiletries - ശുചീകരണ സാമഗ്രികള്‍ ')
    needkit_util = models.BooleanField(verbose_name='Kitchen utensil - അടുക്കള സാമഗ്രികള്‍')
    needrescue = models.BooleanField(verbose_name='Need rescue - രക്ഷാപ്രവർത്തനം ആവശ്യമുണ്ട്')

    detailwater = models.CharField(max_length=250, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailfood = models.CharField(max_length=250, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailcloth = models.CharField(max_length=250, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്‍റെ വിവരങ്ങള്‍', blank=True)
    detailmed = models.CharField(max_length=250, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്‍റെ  വിവരങ്ങള്‍', blank=True)
    detailtoilet = models.CharField(max_length=250, verbose_name='Details for required toiletries - ആവശ്യമായ  ശുചീകരണ സാമഗ്രികള്‍', blank=True)
    detailkit_util = models.CharField(max_length=250, verbose_name='Details for required kitchen utensil - ആവശ്യമായ അടുക്കള സാമഗ്രികള്‍', blank=True)
    detailrescue = models.CharField(max_length=250, verbose_name='Details for rescue action - രക്ഷാപ്രവർത്തനം വിവരങ്ങള്', blank=True)

    needothers = models.CharField(max_length=500, verbose_name="Other needs - മറ്റു ആവശ്യങ്ങള്‍", blank=True)
    status = models.CharField(
        max_length = 10,
        choices = status_types,
        default = 'new'
    )
    supply_details = models.CharField(max_length=100, blank=True)
    dateadded = models.DateTimeField(auto_now_add=True)

    def summarise(self):
        out = ""
        if(self.needwater):
            out += "Water Requirements :\n {}".format(self.detailwater)
        if(self.needfood):
            out += "\nFood Requirements :\n {}".format(self.detailfood)
        if(self.needcloth):
            out += "\nCloth Requirements :\n {}".format(self.detailcloth)
        if(self.needmed):
            out += "\nMedicine Requirements :\n {}".format(self.detailmed)
        if(self.needtoilet):
            out += "\nToilet Requirements :\n {}".format(self.detailtoilet)
        if(self.needkit_util):
            out += "\nKit Requirements :\n {}".format(self.detailkit_util)
        if(len(self.needothers.strip()) != 0):
            out += "\nOther Needs :\n {}".format(self.needothers)
        return out

    def __str__(self):
        return self.get_district_display() + ' ' + self.location

class Volunteer(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    organisation = models.CharField(max_length=250, verbose_name="Organization (സംഘടന) / Institution")
    address = models.TextField()
    area = models.CharField(
        max_length = 15,
        choices = vol_categories,
        verbose_name = "Area of volunteering"
    )
    is_spoc = models.BooleanField(default=False, verbose_name="Is point of contact")
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Contributor(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=10)
    address = models.TextField()
    commodities = models.TextField(verbose_name="What you can contribute. ( സംഭാവന ചെയ്യാന്‍ ഉദ്ദേശിക്കുന്ന സാധനങ്ങള്‍ ) -- Eg: Shirts, torches etc ")
    status = models.CharField(
        max_length = 10,
        choices = contrib_status_types,
        default = 'new'
    )

    def __str__(self):
        return self.name + ' ' + self.get_district_display()


class DistrictManager(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' ' + self.get_district_display()

class DistrictNeed(models.Model):
    district = models.CharField(
        max_length = 15,
        choices = districts,
    )
    needs = models.TextField(verbose_name="Items required")
    cnandpts = models.TextField(verbose_name="Contacts and collection points") #contacts and collection points

    def __str__(self):
        return self.get_district_display()


class DistrictCollection(models.Model):
    district = models.CharField(
        max_length=15,
        choices=districts
    )
    collection = models.TextField(
        verbose_name="Details of collected items"
    )

class RescueCamp(models.Model):
    verbose_name = 'Relief Camp'
    name = models.CharField(max_length=50,verbose_name="Name")
    location = models.TextField(verbose_name="Address",blank=True,null=True)
    district = models.CharField(
        max_length=15,
        choices=districts
    )
    taluk = models.CharField(max_length=50,verbose_name="Taluk")
    village = models.CharField(max_length=50,verbose_name="Village")
    contacts = models.TextField(verbose_name="Phone Numbers",blank=True,null=True)
    data_entry_user = models.ForeignKey(User,models.SET_NULL,blank=True,null=True)
    map_link = models.CharField(max_length=250, verbose_name='Map link',blank=True,null=True,help_text="Copy and paste the full Google Maps link")
    latlng = models.CharField(max_length=100, verbose_name='GPS Coordinates', blank=True,help_text="Comma separated latlng field. Leave blank if you don't know it")
    class Meta:
        verbose_name = 'Relief Camp'
    def __str__(self):
        return self.name


class Person(models.Model):
    name = models.CharField(max_length=30,blank=False,null=False,verbose_name="Name - പേര്")
    phone = models.CharField(max_length=11,null=True,blank=True,verbose_name='Mobile - മൊബൈൽ')
    age = models.IntegerField(null=True,blank=True,verbose_name="Age - പ്രായം")
    gender = models.IntegerField(
        choices = gender,
        verbose_name='Gender - ലിംഗം',
        null=True,blank=True
    )
    address = models.TextField(max_length=150,null=True,blank=True,verbose_name="Address - വിലാസം")
    district = models.CharField(
        max_length = 15,
        choices = districts,
        verbose_name='District - ജില്ല',
        null=True,blank=True
    )
    notes = models.TextField(max_length=500,null=True,blank=True,verbose_name='Notes - കുറിപ്പുകൾ')
    camped_at = models.ForeignKey(RescueCamp,models.CASCADE,blank=False,null=False,verbose_name='Camp Name - ക്യാമ്പിന്റെ പേര്')
    added_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

templates/base.html
{% load static %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="Description" content="For effective collaboration and communications between authorities, volunteers and public">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <meta property="og:title" content="Kerala Rescue">
  <meta property="og:site_name" content="Kerala Rescue">
  <meta property="og:url" content="https://www.keralarescue.in/">
  <meta property="og:description" content="Help out those affected by the Kerala floods by donating or volunteering">
  <meta property="og:type" content="website">
  <meta property="og:image" content="{% static 'images/keralarescue.png' %}">

  <title>Kerala Rescue</title>

  {# <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/> #}

  {% block css %}
  {% endblock %}

  {% bootstrap_css %}

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

</head>

<body>

 {% block body %}

<nav class="navbar">
    <div class="col-sm-4 col-xs-4">
      <a href="/">
        <img src="{% static 'images/kerala-government.jpg' %}" class="nav-logo" style="float:left">
      </a>
    </div>
    <div class="col-sm-4 col-xs-4 text-center">
    {% if not request.path == '/' %}
        <a class="brand-logo" href="/">keralarescue</a>
    {% endif %}
    </div>
    <div class="col-sm-4 col-xs-4">
      <a href="http://www.itmission.kerala.gov.in/">
      <img src="{% static 'images/it-mission.png' %}" class="nav-logo" style="float: right;">
      </a>
      <a href="/ieee/"><img src="{% static 'images/ieeelogo.png' %}" class="nav-logo" style="float: right;margin-right: 6px;"></a>
    </div>
</nav>
<div class="container">

{% block content %}
{% endblock %}

</div>

{% endblock %}


<footer class="footer">
  <div class="container text-center">
    <a href="/disclaimer" style="font-weight:bold">Disclaimer</a>
    <span>&nbsp;|&nbsp;</span>
    <a href="https://github.com/IEEEKeralaSection/rescuekerala/" target="_blank">GitHub</a>
    {# &nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;&nbsp; #}
    {# <a href="/ieee"><img src="{% static 'images/ieeelogo.png' %}" class="footer-logo"></a> #}
  </div>
</footer>

<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
{% bootstrap_javascript %}

{% block javascript %}
{% endblock %}

<!-- This site was developed under IEEE by
    Biswas - https://biswaz.github.io/
    and
    Shameel Kadannamanna - https://shameelsadaka.github.io/
  -->


</body>

</html>

templates/dmodash.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% load bootstrap3 %}

<div class="container text-center">
    <h1 class="main-logo">kerala<span style="font-weight: normal;">rescue  DMO Portal</span></h1>
    <p style="margin-bottom:20px;">
        <i>Please Select the district to view stats </i><br/>
  </p>
<form method="get" action="/dmoinfo"  class="simple-form">
    <div class="form-group"><label class="control-label" for="id_district">Districts - ജില്ല</label><select name="district" class="form-control" title="" required id="id_district">
    <option value="" selected>---------</option>
  
    <option value="tvm">Thiruvananthapuram - തിരുവനന്തപുര</option>
  
    <option value="ptm">Pathanamthitta - പത്തനംതിട</option>
  
    <option value="alp">Alappuzha - ആലപ്പുഴ</option>
  
    <option value="ktm">Kottayam - കോട്ടയം</option>
  
    <option value="idk">Idukki - ഇടുക്കി</option>
  
    <option value="mpm">Malappuram - മലപ്പുറം</option>
  
    <option value="koz">Kozhikode - കോഴിക്കോട</option>
  
    <option value="wnd">Wayanad - വയനാട്</option>
  
    <option value="knr">Kannur - കണ്ണൂർ</option>
  
    <option value="ksr">Kasaragod - കാസർഗോഡ്</option>
  
    <option value="pkd">Palakkad - പാലക്കാട്</option>
  
    <option value="tcr">Thrissur - തൃശ്ശൂർ</option>
  
    <option value="ekm">Ernakulam - എറണാകുളം</option>
  
    <option value="kol">Kollam - കൊല്ലം</option>
  
  </select> 
  <br>
  <input type="submit" class="btn btn-primary">

</div>


</form>
</div>

  {% endblock %}

templates/dmoinfo.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% load bootstrap3 %}

<div class="container text-center">
    <h1 class="main-logo">kerala<span style="font-weight: normal;">rescue  DMO Portal</span></h1>
    <p style="margin-bottom:20px;">
        <i>Stats for your District </i><br/>
  </p>

  <div class="row">
    <div class="col-xs-4" style="font-size:  30px">
        Volunteers
        <br> {{volcount}}
        <br>Registered</div>
    <div class="col-xs-4" style="font-size:  30px">
        Contributors<br>
    {{conserve}} Served 
    <br>
    from {{contotal}}</div>
    <div class="col-xs-4" style="font-size:  30px">
            Requests<br>
        {{reqserve}} Served 
        <br>
        from {{reqtotal}}</div>
  
  </div>



</div>

  {% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% load bootstrap3 %}

<div class="container text-center">
    <h1 class="main-logo">kerala<span style="font-weight: normal;">rescue</span></h1>
    <p style="margin-bottom:20px;">
        <i>An initiative by Govt. of Kerala, Kerala State IT Mission and IEEE Kerala Section<br>
        For effective collaboration and communications between authorities, volunteers and public </i><br/>
        <strong>ദുരിതാശ്വാസ പ്രവര്‍ത്തനങ്ങളും രക്ഷാ ദൗത്യങ്ങളും ഏകോപിപ്പിക്കാന്‍</strong><br/>
    <b><a href="{% static 'images/msg_cm.jpg' %}">Message from Hon. Chief Minister of Kerala</a></b>
  </p>
    <a href="/request" class="home-button card" role="button">
        {% bootstrap_icon "grain" %}
        <span class="text">
            Request<br/>for help<br/>
            <span class="ml small">സഹായം അഭ്യര്‍ഥിക്കാന്‍</span>
        </span>
    </a>
    <a href="/reg_contrib" class="home-button card" role="button">
        {% bootstrap_icon "apple" %}
        <span class="text">
            To Contribute<br/>
            <span class="ml small">സംഭാവന നല്‍കാന്‍</span>
        </span>
    </a>
    <a href="/district_needs/" class="home-button card" role="button">
        {% bootstrap_icon "map-marker" %}
        <span class="text">
            DISTRICT NEEDS &amp; COLLECTION CENTERS<br></span>
            <span class="ml small">ജില്ലകളിലെ ആവശ്യങ്ങള്‍</span>
        </span>
    </a>
    <a href="/volunteer" class="home-button card" role="button">
        {% bootstrap_icon "user" %}
        <span class="text">
            Register as<br/>a volunteer
            <span class="ml small">വൊളന്‍റീയര്‍ ആകാന്‍</span>
        </span>
    </a>
    <a href="/map" class="home-button card" role="button">
        {% bootstrap_icon "globe" %}
        <span class="text">
            Request Map<br/>
            <span class="ml small">സഹായം ആവശ്യമായ സ്ഥലങ്ങൾ</span>
        </span>
    </a> 
    <a href="{% url 'contactus' %}" class="home-button card" role="button">
        {% bootstrap_icon "phone" %}
        <span class="text">
            Contact <br>INFO<br/>
            <span class="ml small">ഞങ്ങളുമായി ബന്ധപ്പെടാന്‍</span>
        </span>
    </a>
    <a href="/requests" class="home-button card" role="button">
      {% bootstrap_icon "list" %}
      <span class="text">
        Registered Requests<br/>
        <span class="ml small">ഇതു വരെ ആവശ്യപ്പെട്ടവ</span>
      </span>
    </a>
    <a href="/relief_camps" class="home-button card" role="button">
        {% bootstrap_icon "home" %}
        <span class="text">
          Relief Camps<br/>
          <span class="ml small">ദുരിതാശ്വാസ ക്യാമ്പുകൾ</span>
        </span>
      </a>
    <p class="home-info">
        Contact Control Room or Disaster Management Cell or District Administration for any support.<br>
        Volunteers may contact District Project Managers for support related to volunteering and contributions<br>
        <br/>
        സഹായത്തിനായി വൊളന്‍റീയര്‍മാര്‍ തയ്യാറാണ്. സഹായം ആവശ്യമെങ്കില്‍ ഒരോ ജില്ലയിലെയും നിയോഗിക്കപെട്ട ഉദ്യോഗസ്ഥരുമായി ബന്ധപ്പെടാം
    </p>
</div>
{% endblock %}

templates/map.html
{% load static %}

<!doctype html><html lang="en"><head><meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"><meta name="theme-color" content="#000000">
    <link rel="manifest" href="/kerala-flood-map/manifest.json"><link rel="shortcut icon" href="/kerala-flood-map/favicon.ico">
    <title>Kerala Flood Map</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.3/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
    <link href="{% static 'css/map.css'%}" rel="stylesheet"></head>
    <body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div>
        <link rel="stylesheet" href="https://unpkg.com/tachyons@4.10.0/css/tachyons.min.css"/>
        <script type="text/javascript" src="{% static 'js/map.js'%}"></script></body></html>